config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions, only: %i(show new create update destroy) do
    collection do
      put :update_all
      get :upload
      post :import
    end
  end

  resources :feeds, only: :index
  resources :items, only: :index
  resources :tags, only: :index
  resource :initial, only: :show
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resource :crawler, only: :create
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :feed
  acts_as_taggable

  accepts_nested_attributes_for :feed

  validates :user_id, presence: true
  validates :title, length: { maximum: 255 }
  validates :feed_id, uniqueness: { scope: :user_id }

  default_scope -> { order(created_at: :desc) }

  scope :search, lambda { |conditions|
    scope = self
    conditions[:tag].presence.try do |tag_names|
      scope = scope.tagged_with(tag_names)
    end
    scope = scope.page(conditions[:page])
    scope
  }

  scope :url, ->(url) { joins(:feed).merge(Feed.where(url: url)) }
  scope :default, -> { where(hide_default: false) }

  class AlreadySubscribed < StandardError
    attr_reader :subscription

    def initialize(subscription)
      @subscription = subscription
    end
  end

  class FeedNotFound < StandardError; end

  def self.prefetch(url)
    require_not_subscribed(url)

    feed_url = Feedbag.find(url)[0]
    raise FeedNotFound unless feed_url
    require_not_subscribed(feed_url)

    feed = Feed.find_or_initialize_by(url: feed_url)
    feed.load! if feed.new_record?

    new(feed: feed)
  end

  def self.require_not_subscribed(url)
    url(url).first.try! do |subscription|
      raise AlreadySubscribed.new(subscription)
    end
  end

  # XXX: もっとスマートにしたい
  def subscribe!
    persisted_feed = Feed.find_by(url: feed.url)
    if persisted_feed
      self.feed = persisted_feed
    else
      feed.load!
      feed.save!
    end
    save!
  end

  def user_title
    title.presence || feed.title
  end

  def tags_string
    tags.map(&:name).join(', ')
  end
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  def show
    @subscription = owned_subscriptions.preload(:feed).find(params[:id])
    @items = @subscription.feed.items.page(params[:page])
  end

  def new
    url = params.require(:url)
    @subscription = owned_subscriptions.prefetch(url)
    @items = @subscription.feed.items.first(Kaminari.config.default_per_page)
    render :show
  rescue Subscription::FeedNotFound
    flash['alert'] = I18n.t('messages.feed_not_found')
    render json: { type: 'feedNotFound' }, status: :unprocessable_entity
  rescue Subscription::AlreadySubscribed => e
    flash[:notice] = I18n.t('messages.feed_already_registered', url: e.subscription.feed.url)
    render json: { id: e.subscription.id }
  end

  def create
    @subscription = owned_subscriptions.build(params_for_create)
    @subscription.subscribe!
    render json: { id: @subscription.id }
  end

  def update
    @subscription = owned_subscriptions.find(params[:id])
    @subscription.update!(params_for_update)
    render json: { id: @subscription.id }
  end

  def import
    opml_file = params[:file]
    return render json: { error: 'Select OPML file.' }, status: :unprocessable_entity if opml_file.blank?

    OPML.import!(opml_file.tempfile, current_user)

    render_json_ok
  rescue OPML::InvalidFormat
    render json: { error: 'Invalid file format.' }, status: :unprocessable_entity
  end

  def destroy
    Subscription.destroy(params[:id])
    render_json_ok
  end

  private

  def params_for_create
    subscription_params.permit(:title, :tag_list, :hide_default, feed_attributes: [:url])
  end

  def params_for_update
    subscription_params.permit(:title, :tag_list, :hide_default)
  end

  def owned_subscriptions
    current_user.subscriptions
  end

  def subscription_params
    params.require(:subscription)
  end
end

app/views/subscriptions/index.html.haml
%h1.page-header Feeds

= render 'tags'

%table.table.table-hover
  %tr
    %th
    %th= Feed.human_attribute_name :title
    %th Latest
    %th= Feed.human_attribute_name :tags
    %th Apply
    %th Delete
    %th
  - @subscriptions.each do |subscription|
    %tr{ class: "_#{subscription.id}" }
      = form_for subscription, remote: true, class: %w[form form-inline] do |f|
        %td
          = link_to '■', f.object
        %td.title
          = f.text_field :title, size: 50, class: 'form-control', placeholder: subscription.feed.title
        %td.latest
          = link_to truncate(subscription.feed.latest_item.try(:title), length: 30), subscription, target: '_blank'
        %td.tag
          = f.text_field :tag_list, class: 'form-control', value: subscription.tags_string
        %td
          = f.button class: %w[btn btn-primary btn-sm] do
            %span.glyphicon.glyphicon-ok
        %td
          = link_to subscription_path(subscription), method: :delete, class: %w[btn btn-sm btn-danger], data: { confirm: 'Delete?' } do
            &cross;
        %td.response

= paginate @subscriptions

app/views/subscriptions/show.html.haml
%h1.page-header= link_to @subscription.user_title, @subscription.feed.link_url

%p= @subscription.feed.description
%small
  = link_to @subscription.feed.url, @subscription.feed.url, target: '_blank'

%p= render @items, hide_feed: true

= paginate @items